--문제1.
--
--다음과 같은 테이블을 생성하고 데이터를 insert해보세요.
--테이블 제약조건은 아래와 같습니다. 
--조건) M_NAME 는 가변문자형 20byte, 널값을 허용하지 않음
--조건) M_NUM 은 숫자형 5자리, PRIMARY KEY 이름(mem_memnum_pk) 
--조건) REG_DATE 는 날짜형, 널값을 허용하지 않음, UNIQUE KEY 이름:(mem_regdate_uk)
--조건) GENDER 고정문자형 1byte, CHECK제약 (M, F)
--조건) LOCA 숫자형 4자리, FOREIGN KEY ? 참조 locations테이블(location_id) 이름:(mem_loca_loc_locid_fk)

CREATE TABLE MEM (
    M_NAME VARCHAR2(20) NOT NULL,
    M_NUM NUMBER(5),
    REG_DATE DATE NOT NULL,
    GENDER CHAR(1),
    LOCA NUMBER(4),
    CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY (M_NUM),
    CONSTRAINT MEM_REGDATE_UK UNIQUE (REG_DATE),
    CONSTRAINT MEM_GENDER_CK CHECK(GENDER IN('M', 'F')),
    CONSTRAINT MEM_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)
);

INSERT INTO MEM(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('AAA', 1, TO_DATE('2018-07-01', 'YYYY-MM-DD'), 'M', 1800);

INSERT INTO MEM(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('BBB', 2, TO_DATE('2018-07-02', 'YYYY-MM-DD'), 'F', 1900);

INSERT INTO MEM(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('CCC', 3, TO_DATE('2018-07-03', 'YYYY-MM-DD'), 'M', 2000);

INSERT INTO MEM(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('DDD', 4, SYSDATE, 'M', 2000);

SELECT * FROM MEM;

--문제2.
--
--도서 대여 이력 테이블을 생성하려 합니다.
--도서 대여 이력 테이블은
--대여번호(숫자) PK, 대출도서번호(문자), 대여일(날짜), 반납일(날짜), 반납여부(Y/N)
--를 가집니다.
--적절한 테이블을 생성해 보세요.
DROP TABLE BOOKHISTORY;
CREATE TABLE BOOKHISTORY(
    BOOK_NUM NUMBER(4),
    BOOK_ID VARCHAR(30) NOT NULL,
    BOOK_DATE DATE DEFAULT SYSDATE,
    BOOK_DUEDATE DATE DEFAULT SYSDATE + 7,
    BOOK_CHECK CHAR(1),
    CONSTRAINT BH_BOOK_NUM_PK PRIMARY KEY (BOOK_NUM),
    CONSTRAINT BH_BOOK_ID_UK UNIQUE (BOOK_ID),
    CONSTRAINT BH_BOOK_CHECK_CK CHECK(BOOK_CHECK IN('Y', 'N'))
);

ALTER TABLE BOOKHISTORY MODIFY BOOK_ID VARCHAR2(30);

ALTER TABLE BOOKHISTORY DROP CONSTRAINT BH_BOOK_ID_UK;

DESC BOOKHISTORY;
SELECT * FROM BOOKHISTORY;

INSERT INTO BOOKHISTORY(BOOK_NUM, BOOK_ID, BOOK_CHECK) 
VALUES(1, 'IT-SQL-123123', 'Y');
UPDATE BOOKHISTORY SET BOOK_CHECK = 'N' WHERE BOOK_NUM = 1;

INSERT INTO BOOKHISTORY(BOOK_NUM, BOOK_ID, BOOK_DATE, BOOK_CHECK)
VALUES(2, 'IT-JAVA-111111', '24/06/07', 'Y');

INSERT INTO BOOKHISTORY
VALUES(3, 'IT-HTML-321321', '24/06/16', '24/06/23', 'N');

UPDATE BOOKHISTORY SET BOOK_DUEDATE = BOOK_DATE + 7 
WHERE TO_CHAR(BOOK_DUEDATE, 'YY/MM/DD') = TO_CHAR(SYSDATE + 7, 'YY/MM/DD');
