DROP TABLE DEPTS;
CREATE TABLE DEPTS AS (SELECT * FROM DEPARTMENTS);
SELECT * FROM DEPTS;
--3. 프로시저명 DEPTS_PROC
--- 부서번호, 부서명, 작업 flag(I: insert, U:update, D:delete)을 매개변수로 받아 
--DEPTS테이블에 각각 flag가 i면 INSERT, u면 UPDATE, d면 DELETE 하는 프로시저를 생성합니다.
--- 그리고 정상종료라면 commit, 예외라면 롤백 처리하도록 처리하세요.
--- 예외처리도 작성해주세요.

CREATE OR REPLACE PROCEDURE DEPTS_PROC
    (P_DEPTS_ID IN DEPARTMENTS.DEPARTMENT_ID%TYPE,
     P_DEPTS_NAME IN DEPARTMENTS.DEPARTMENT_NAME%TYPE,
     FLAG IN VARCHAR2
     )
IS
BEGIN
    IF UPPER(FLAG) = 'I' THEN
        INSERT INTO DEPTS(DEPARTMENT_ID, DEPARTMENT_NAME)
        VALUES (P_DEPTS_ID, P_DEPTS_NAME);
    ELSIF UPPER(FLAG) = 'U' THEN
        UPDATE DEPTS SET DEPARTMENT_NAME = P_DEPTS_NAME
        WHERE DEPARTMENT_ID = P_DEPTS_ID;
    ELSIF UPPER(FLAG) = 'D' THEN
        DELETE FROM DEPTS WHERE DEPARTMENT_ID = P_DEPTS_ID;
    END IF;
    
    COMMIT;
    
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('예외입력입니다.');
END;

EXEC DEPTS_PROC(280, 'ADMIN', 'I');
EXEC DEPTS_PROC(280, 'ADMINISTRATOR', 'U');
SELECT * FROM DEPTS;

--6. 프로시저명 - SALES_PROC
--- sales테이블은 오늘의 판매내역이다.
--- day_of_sales테이블은 판매내역 마감시 오늘 일자의 총매출을 기록하는 테이블이다.
--- 마감시 sales의 오늘날짜 판매내역을 집계하여 day_of_sales에 집계하는 프로시저를 생성해보세요.
--조건) day_of_sales의 마감내역이 이미 존재하면 업데이트 처리
DROP TABLE SALES;
CREATE TABLE SALES(
    SNO NUMBER(5) CONSTRAINT SALES_PK PRIMARY KEY, -- 번호
    NAME VARCHAR2(30), -- 상품명
    TOTAL NUMBER(10), --수량
    PRICE NUMBER(10), --가격
    REGDATE DATE DEFAULT SYSDATE --날짜
);

DROP TABLE DAY_OF_SALES;
CREATE TABLE DAY_OF_SALES(
    REGDATE DATE,
    FINAL_TOTAL NUMBER(10)
);

DESC SALES;

INSERT INTO SALES(SNO, NAME, TOTAL, PRICE) VALUES (1, '아메리카노', 3, 1000);
INSERT INTO SALES(SNO, NAME, TOTAL, PRICE) VALUES (2, '콜드브루', 2, 2000);
INSERT INTO SALES(SNO, NAME, TOTAL, PRICE) VALUES (3, '돌체라떼', 1, 3000);

SELECT * FROM SALES;    

CREATE OR REPLACE PROCEDURE SALES_PROC
    (
     P_REGDATE DATE := SYSDATE
     )
IS 
    CNT NUMBER := 0;     -- 날짜 확인 변수
    P_TOTAL NUMBER := 0; -- 토탈값 저장 변수
BEGIN
    SELECT COUNT(*)
    INTO CNT -- 개수를 CNT 에 저장
    FROM DAY_OF_SALES
    WHERE TO_CHAR(REGDATE,'YYYYMMDD') = TO_CHAR(P_REGDATE, 'YYYYMMDD');
    
    SELECT FINAL_TOTAL
    INTO P_TOTAL
    FROM (SELECT SUM(TOTAL * PRICE) AS FINAL_TOTAL 
          FROM SALES 
          GROUP BY TO_CHAR(REGDATE, 'YY/MM/DD')
          );
        
    IF CNT > 0 THEN 
        UPDATE DAY_OF_SALES
        SET FINAL_TOTAL = P_TOTAL 
        WHERE TO_CHAR(REGDATE, 'YYYYMMDD') = TO_CHAR(P_REGDATE, 'YYYYMMDD');
    ELSE
        INSERT INTO DAY_OF_SALES VALUES(P_REGDATE, P_TOTAL);
    END IF;
    
    COMMIT;
    
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
END;

EXEC SALES_PROC(SYSDATE);
SELECT * FROM DAY_OF_SALES;