-- ORDER BY 정렬
SELECT * FROM EMPLOYEES ORDER BY SALARY;    -- 아무것도 안적으면 ASC
SELECT * FROM EMPLOYEES ORDER BY SALARY ASC;    -- 오름차순 null 값은 가장 마지막이다.
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC;    -- 내림차순.

SELECT FIRST_NAME, SALARY * 12 AS 연봉 FROM EMPLOYEES ORDER BY 연봉;    -- 연봉 별칭 기준 오름차순

-- 정렬을 2개 이상 COLUMN 으로 시킬 수 있다. ,(콤마) 를 통해 연결.
-- 부서번호가 높은 사람들 중에서, 급여가 높은 사람들 기준 정렬
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC, SALARY DESC;

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'SA_MAN') ORDER BY FIRST_NAME ASC;

