-- NULL 처리 함수

 -- NVL, NULL 일 경우 처리
 -- NVL(대상값, NULL일 경우 처리)
 SELECT NVL(1000, 0), NVL(NULL, 0) FROM DUAL;
 SELECT NULL + 1000 FROM DUAL; -- NULL 에 연산을 하면 NULL 이 나온다.

 SELECT FIRST_NAME, SALARY, COMMISSION_PCT, 
        SALARY + SALARY * COMMISSION_PCT AS 최종급여 -- COMMISSION_PCT 가 NULL 이면 NULL 값만 나온다.
 FROM EMPLOYEES; 
 
 SELECT FIRST_NAME, SALARY, COMMISSION_PCT, 
        SALARY + SALARY * NVL(COMMISSION_PCT, 0) AS 최종급여 
 FROM EMPLOYEES;

 -- NVL2(대상값, NULL이 아닐경우, NULL일 경우)
 SELECT NVL2(NULL, 'NULL이 아닙니다.', 'NULL입니다.') AS RESULT1 FROM DUAL;

 SELECT FIRST_NAME, SALARY, COMMISSION_PCT,  
        NVL2(COMMISSION_PCT, SALARY + SALARY * COMMISSION_PCT, SALARY) AS 최종급여 
 FROM EMPLOYEES;
        
 -- COALESCE(값, 값, 값,... )
 -- NULL이 아닌 첫번째 값을 반환
 SELECT COALESCE(1, 2, 3) AS RESULT1,               -- 1
        COALESCE(NULL, 2, 3, 4) AS RESULT2,         -- 2
        COALESCE(NULL, NULL, NULL, 4) AS RESULT3,   -- 4
        COALESCE(NULL, NULL, 3, NULL) AS RESULT4,   -- 3
        COALESCE(NULL, NULL, NULL, NULL) AS RESULT5 -- NULL
 FROM DUAL;
 
 -- NVL 처럼 사용 가능
 SELECT COALESCE(COMMISSION_PCT, 0) AS COMMISSION_PCT FROM EMPLOYEES;
 