-- ROLLUP
-- GROUP BY 절과 함께 사용
-- 상위그룹의 총계를 나타냅니다.
SELECT   DEPARTMENT_ID,
         SUM(SALARY) AS 급여합,
         ROUND(AVG(SALARY), 2) AS 급여평균
FROM     EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID);

SELECT   DEPARTMENT_ID AS 부서ID,
         JOB_ID AS 직종,
         SUM(SALARY) AS 급여합,
         ROUND(AVG(SALARY), 2) AS 급여평균
FROM     EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID;

SELECT   DEPARTMENT_ID AS 부서ID,
         JOB_ID AS 직종,
         SUM(SALARY) AS 급여합,
         ROUND(AVG(SALARY), 2) AS 급여평균
FROM     EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID;

-- CUBE
-- ROLLUP 의 총계에 서브그룹의 총계가 추가됨
SELECT   DEPARTMENT_ID,
         JOB_ID,
         SUM(SALARY),
         ROUND(AVG(SALARY), 2)
FROM     EMPLOYEES
GROUP BY CUBE(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID;

-- GROUPING
-- GROUP BY 로 만들어진 행이면 0 반환
-- ROLLUP, CUBE 로 만들어진 행이면 1 반환
SELECT
    DEPARTMENT_ID AS 부서ID,
    JOB_ID AS 직무,
    ROUND(AVG(SALARY), 2) AS 급여평균,
    GROUPING(DEPARTMENT_ID),
    GROUPING(JOB_ID)
FROM
    EMPLOYEES
GROUP BY
    ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY
    DEPARTMENT_ID;

-- GROUPING 을 사용하여 다르게 표시 가능
SELECT 
    DECODE(GROUPING(DEPARTMENT_ID), 1, '총계', DEPARTMENT_ID) AS 부서ID,
    DECODE(GROUPING(JOB_ID), 1, '소계', JOB_ID) AS 직무,
    ROUND(AVG(SALARY), 2) AS 급여평균
FROM 
    EMPLOYEES
GROUP BY
    ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY
    DEPARTMENT_ID;
    
    
