-- 트랜잭션
-- 오직 DML 문에 대해서만 트랜잭션을 수행할 수 있습니다. (DDL 문은 자동 커밋됨)

-- 오토커밋 확인
SHOW AUTOCOMMIT;
-- 오토커밋 ON
SET AUTOCOMMIT ON;
SET AUTOCOMMIT OFF;

-- SAVEPOINT
SELECT * FROM DEPTS;
COMMIT;

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 10;

SAVEPOINT DEPT10; -- 세이브포인트(트랜잭션의 지점)

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 20;

SAVEPOINT DEPT20;

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 30;

-- 세이브포인트로 돌아가기
ROLLBACK TO DEPT20;
ROLLBACK TO DEPT10;
ROLLBACK;

SELECT * FROM DEPTS;

INSERT INTO DEPTS VALUES (280, 'AA', NULL, 1800);
COMMIT;